config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users
  resources :vehicles do
    resource :likes, only: [:create, :destroy]
    collection do
      get 'likes'
    end

    resources :chats, only: [:create], shallow: true

    resources :requests, only: [:index, :create, :destroy]
    resources :matchings, only: [:create, :destroy]
  end

  get 'matchings', to: 'matchings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :user_id, uniqueness: { scope: :vehicle_id }
end

app/models/matching.rb
class Matching < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :user_id, presence: true
  validates :vehicle_id, presence: true
  validates :user_id, uniqueness: { scope: :vehicle_id}
  validates :vehicle_id, uniqueness: { scope: :user_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vehicles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_vehicles, through: :likes, source: :vehicle
  has_many :chats, dependent: :destroy
  has_many :matchings, dependent: :destroy
  has_many :requests, dependent: :destroy

  authenticates_with_sorcery!

  def like(vehicle)
    like_vehicles << vehicle
  end

  def own?(object)
    id == object.user_id
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  mount_uploader :vehicle_image, VehicleImageUploader
  belongs_to :user
  has_many :chats, dependent: :destroy
  has_one :matching, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :users, through: :matchings

  validates :vehicle_name, presence: true
  validates :description, presence: true

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def create
        @chat = current_user.chats.build(chat_params)
        if @chat.save
            redirect_to vehicle_path(@chat.vehicle) #成功メッセージを追記
        else
            redirect_to vehicle_path(@chat.vehicle) #失敗メッセージを追記
        end
    end

    private

    def chat_params
        params.require(:chat).permit(:body).merge(vehicle_id: params[:vehicle_id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        vehicle = Vehicle.find(params[:vehicle_id])
        current_user.like(vehicle)
        redirect_to vehicles_path
    end

    def destroy
        @like = Like.find_by(user_id: current_user.id, vehicle_id: params[:vehicle_id])
        @like.destroy
        redirect_to vehicles_path
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

    def create
        current_user.requests.create(vehicle_id: request_params[:vehicle_id])
        redirect_to vehicle_path(request_params[:vehicle_id])
    end
    
    def destroy
        @request = Request.find(params[:id])
        @request.destroy!
        @vehicle = Vehicle.find(params[:vehicle_id])
        redirect_to vehicle_url(@vehicle)
    end

    def index
        @requests = Request.where(vehicle_id: params[:vehicle_id])
    end


    private
    def request_params
        params.permit(:vehicle_id)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: %i[create new]


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :salt)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    def index
        @vehicles = Vehicle.all.includes(:user).order(created_at: :desc)
    end

    def show
        @vehicle = Vehicle.find(params[:id])
        @chat = Chat.new
        @chats = @vehicle.chats.includes(:user).order(created_at: :asc)
        @request = Request.find_by(user_id: current_user.id)
        @matchings = Matching.all
    end

    def new
        @vehicle = Vehicle.new
    end

    def create
        @vehicle = current_user.vehicles.new(vehicle_params)
        if @vehicle.save
            redirect_to vehicles_path
        else
            render :new
        end
    end

    def edit
        @vehicle = current_user.vehicles.find(params[:id])
    end

    def update
        @vehicle = current_user.vehicles.find(params[:id])

        if @vehicle.update(vehicle_params)
            redirect_to vehicles_path
        else
            render :edit
        end
    end

    def destroy
        @vehicle = current_user.vehicles.find(params[:id])
        @vehicle.destroy
        redirect_to vehicles_path
    end

    def likes
        @likes_vehicles = current_user.like_vehicles.includes(:user).order(created_at: :desc)
    end

    private
    def vehicle_params
        params.require(:vehicle).permit(:vehicle_name, :description, :vehicle_image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <a class="navbar-brand" href="/">
      <%= image_tag 'logo.png' %>
    </a>
    
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to 'ログイン', login_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="copyright">
          <p>Copyright © 2022. Yosuke Kubota</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            予約
          </a>

          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to '探す', vehicles_path, class: 'dropdown-item' %>
            <%= link_to '作成', new_vehicle_path, class: 'dropdown-item' %>
            <%= link_to 'お気に入り一覧', likes_vehicles_path, class: 'dropdown-item' %>
            <%= link_to '予約済み一覧', matchings_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="header-profile">
            <%= image_tag 'sample', size: '40x40', class: 'rounded-circle mr15'%>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item"><%= current_user.name %></div>
            <div class="dropdown-divider"></div>
            <%= link_to 'プロフィール', '#', class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>