config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users
  resources :vehicles do
    resource :likes, only: [:create, :destroy]
    collection do
      get 'likes'
    end

    resources :chats, only: [:create], shallow: true

    resources :requests, only: [:index, :create, :destroy]
    resources :matchings, only: [:create, :destroy]
  end

  get 'matchings', to: 'matchings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :user_id, uniqueness: { scope: :vehicle_id }
end

app/models/matching.rb
class Matching < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :user_id, presence: true
  validates :vehicle_id, presence: true
  validates :user_id, uniqueness: { scope: :vehicle_id}
  validates :vehicle_id, uniqueness: { scope: :user_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vehicles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_vehicles, through: :likes, source: :vehicle
  has_many :chats, dependent: :destroy
  has_many :matchings, dependent: :destroy
  has_many :requests, dependent: :destroy

  authenticates_with_sorcery!

  def like(vehicle)
    like_vehicles << vehicle
  end

  def own?(object)
    id == object.user_id
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  mount_uploader :vehicle_image, VehicleImageUploader
  belongs_to :user
  has_many :chats, dependent: :destroy
  has_one :matching, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :users, through: :matchings

  validates :vehicle_name, presence: true
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login


    private
    
    def not_authenticated
        redirect_to login_path, danger: "ログインしてください"
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def create
        @chat = current_user.chats.build(chat_params)
        if @chat.save
            redirect_to vehicle_path(@chat.vehicle) #成功メッセージを追記
        else
            redirect_to vehicle_path(@chat.vehicle) #失敗メッセージを追記
        end
    end

    private

    def chat_params
        params.require(:chat).permit(:body).merge(vehicle_id: params[:vehicle_id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        vehicle = Vehicle.find(params[:vehicle_id])
        current_user.like(vehicle)
        redirect_to vehicles_path
    end

    def destroy
        @like = Like.find_by(user_id: current_user.id, vehicle_id: params[:vehicle_id])
        @like.destroy
        redirect_to vehicles_path
    end
end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController

    def index
        @matchings = Matching.all
    end

    def create
        @matching = Matching.create(vehicle_id: matching_params[:vehicle_id], user_id: matching_params[:user_id])
        Request.where(vehicle_id: matching_params[:vehicle_id]).delete_all
        redirect_to vehicle_requests_url(@matching.vehicle)
    end

    def destroy
        @matching = Matching.find(params[:id])
        @matching.destroy!
        redirect_to vehicles_path
    end

    private

    def matching_params
        params.permit(:vehicle_id, :user_id, :request_id)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

    def create
        current_user.requests.create(vehicle_id: request_params[:vehicle_id])
        redirect_to vehicle_path(request_params[:vehicle_id])
    end
    
    def destroy
        @request = Request.find(params[:id])
        @request.destroy!
        @vehicle = Vehicle.find(params[:vehicle_id])
        redirect_to vehicle_url(@vehicle)
    end

    def index
        @requests = Request.where(vehicle_id: params[:vehicle_id])
    end


    private
    def request_params
        params.permit(:vehicle_id)
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def top; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: %i[create new]


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :salt)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    def index
        @vehicles = Vehicle.all.includes(:user).order(created_at: :desc)
    end

    def show
        @vehicle = Vehicle.find(params[:id])
        @chat = Chat.new
        @chats = @vehicle.chats.includes(:user).order(created_at: :asc)
        @request = Request.find_by(user_id: current_user.id)
        @matchings = Matching.all
    end

    def new
        @vehicle = Vehicle.new
    end

    def create
        @vehicle = current_user.vehicles.new(vehicle_params)
        if @vehicle.save
            redirect_to vehicles_path
        else
            render :new
        end
    end

    def edit
        @vehicle = current_user.vehicles.find(params[:id])
    end

    def update
        @vehicle = current_user.vehicles.find(params[:id])

        if @vehicle.update(vehicle_params)
            redirect_to vehicles_path
        else
            render :edit
        end
    end

    def destroy
        @vehicle = current_user.vehicles.find(params[:id])
        @vehicle.destroy
        redirect_to vehicles_path
    end

    def likes
        @likes_vehicles = current_user.like_vehicles.includes(:user).order(created_at: :desc)
    end

    private
    def vehicle_params
        params.require(:vehicle).permit(:vehicle_name, :description, :vehicle_image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/chats/_chat.html.erb
<%if current_user.own?(chat) %>
    <div class="mycomment">
        <p><%=chat.body%></p>
    </div>
<%else%>
    <div class="fukidasi">
        <div class="faceicon">
            <%= image_tag 'sample' %>
        </div>
        <div class="chatting">
            <div class="says">
                <p><%=chat.body %></p>
            </div>
        </div>
    </div>
<%end%>

app/views/chats/_chats.html.erb
    <table class="table">
      <div id="chats">
        <%= render chats %>
      </div>
    </table>

app/views/chats/_form.html.erb
    <%= form_with model: chat, url: [vehicle, chat], local: true do |f| %>
      <%= f.text_area :body, class: 'form-control' %>
      <div class="text-right">
          <%= f.submit value="送信", class: 'btn btn-primary' %>
      </div>
    <% end %>

app/views/matchings/index.html.erb
<div class="container pt-3">
  <h1>予約済み一覧</h1>
  <div class="row">
    <div class="col-12">
      <div class="row">
        <%= @matchings.each do |matching| %>
          <% if matching.vehicle.user_id == current_user.id or matching.user_id == current_user.id%>
            <%= render 'vehicles/vehicle', { vehicle: matching.vehicle } %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<div class="container applicant-wrapper">
    <h3>承認待ちユーザ一覧</h3>
    <div class="row">
        <% @requests.each do |request| %>
        <div class="col-6">
            <%= link_to request.user.name, request.user %>
            <%= link_to "承認", vehicle_matchings_path(request.vehicle, user_id: request.user.id, request_id: request.id), method: :post, class:"mini-green-link-btn font-bold text-line-none" %>
            <%= link_to "却下", vehicle_request_path(request.vehicle, request), method: :delete, class:"mini-red-link-btn font-bold text-line-none" %>
            <br>
        </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー編集</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.text_field :password, class: "form-control" %>
        </div>
        <%= f.submit value="更新", class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <a href="/login">ログインページへ</a>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <h1>ユーザー一覧</h1>
        <table class="table">
            <thead>
                <tr>
                    <th class="mr-1">氏名</th>
                    <th class="mr-1">メールアドレス</th>
                    <th class="mr-1"></th>
                    <th class="mr-1"></th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                    <td><%= link_to user.name, user %></td>
                    <td><%= user.email %></td>
                    <td><%= link_to '編集', edit_user_path(user), class: "btn btn-primary" %></td>
                    <td><%= link_to '削除', user, method: :delete, class: "btn btn-danger"  %></td>
                </tr>
                <% end %>
            </tbody>
        </table>



      <div class='text-center'>
        <%= link_to '新規登録', new_user_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.text_field :password, class: "form-control" %>
        </div>
        <%= f.submit value="登録", class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <a href="/login">ログインページへ</a>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <h1>ユーザー一覧</h1>
        <table class="table">
            <tbody>
                <tr>
                    <th>Name</th>
                    <td><%= @user.name %></td>
                </tr>
                <tr>
                    <th>メールアドレス</th>
                    <td><%= @user.email %></td>
                </tr>
            </tbody>
        </table>
      <div class='text-center'>
        <%= link_to 'ユーザー一覧', users_path %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/_form.html.erb
<%= form_with model: vehicle, local: true do |f| %>
  <div class="form-group">
    <%= f.label :vehicle_name %>
    <%= f.text_field :vehicle_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :vehicle_image %>
    <%= f.file_field :vehicle_image, class: 'form-control mb-3', accept: 'image/*' %>
    <%= f.hidden_field :vehicle_image_cache %>
  </div>
  <div class='mt-3 mb-3'>
    <%= image_tag vehicle.vehicle_image.url,
                  id: 'preview',
                  size: '300x200' %>
  </div>
  <%= f.submit value="投稿", class: "btn btn-primary" %>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="vehicle-id-<%= vehicle.id %>">
    <div class="card">
      <%= image_tag vehicle.vehicle_image_url, class: 'card-img-top', size: '300x200' %>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to vehicle.vehicle_name, vehicle %>
        </h4>
        <div class='mr10 float-right'>
            <% if current_user.own?(vehicle) %>
                <%= link_to edit_vehicle_path(vehicle), id: 'button-edit-#{vehicle.id}' do %>
                    <%= icon 'fa', 'pen' %>
                <% end %>
                <%= link_to vehicle, id: 'button-delete-#{vehicle.id}', method: :delete, data: {confirm: ''} do %>
                    <%= icon 'fas', 'trash' %>
                <% end %>
            <% else %>
                <% if Like.find_by(user_id: current_user.id, vehicle_id: vehicle.id) %>
                    <%= link_to vehicle_likes_path(vehicle.id), method: :delete do %>
                        <i class="fa fa-heart"></i>
                    <% end %>
                <% else %>
                    <%= link_to vehicle_likes_path(vehicle.id), method: :post do %>
                        <i class="far fa-heart"></i>
                    <% end %>
                <% end %>
            <% end %>
        </div>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= icon 'far', 'user' %>
            <%= vehicle.user.name %>
          </li>
          <li class="list-inline-item">
            <%= icon 'far', 'calendar' %>
            <%= l vehicle.created_at, format: :long %>
          </li>
        </ul>
        <p class="card-text"><%= vehicle.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>車両編集</h1>
      <%= render 'form', { vehicle: @vehicle } %>
    </div>
  </div>
</div>

app/views/vehicles/index.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <form>
        <div class="input-group mb-3"><input class="form-control" placeholder="検索ワード" type="search"/>
          <div class="input-group-append"><input type="submit" value="検索" class="btn btn-primary"/></div>
        </div>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @vehicles.present? %>
          <%= render @vehicles %>
        <% else %>
          <p>なし</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/likes.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <form>
        <div class="input-group mb-3"><input class="form-control" placeholder="検索ワード" type="search"/>
          <div class="input-group-append"><input type="submit" value="検索" class="btn btn-primary"/></div>
        </div>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @likes_vehicles.present? %>
            <%= render @likes_vehicles %>
        <% else %>
          <p>なし</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>車両投稿</h1>
      <%= render 'form', { vehicle: @vehicle } %>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1>詳細</h1>
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%= image_tag 'sample.jpg', class: "card-img-top img-fluid", width: '300', height: '200'%>
            </div>
            <div class='col-md-9'>
              <h3 style='display: inline;'><%= @vehicle.vehicle_name %></h3>
              <ul class="list-inline">
                <li class="list-inline-item">by <%= @vehicle.user.name %></li>
                <li class="list-inline-item"><%= @vehicle.created_at %></li>
              </ul>
            </div>
          </div>
          <p><%= @vehicle.description %></p>
        </div>
        <% if @vehicle.matching.present? %>
          <% if @vehicle.matching.user.id == current_user.id %>
            <%= link_to 'キャンセルする', vehicle_matching_path(@vehicle, current_user.matchings.find_by(vehicle_id: @vehicle.id)), method: :delete,class: "btn btn-danger" %>
          <% end %>
        <% end %>
        <% if @vehicle.user_id == current_user.id && @vehicle.matching.present? == false %>
            <%= link_to "承認待ち一覧", vehicle_requests_path(@vehicle), class:"btn btn-primary" %>
        <% elsif @vehicle.matching.present? == false %>
            <% if @request %>
                <%= link_to '申請取消', vehicle_request_path(@vehicle, @request), method: :delete, class: "btn btn-primary" %>
            <% else %>
                <%= link_to '予約申請', vehicle_requests_path(@vehicle), method: :post, class: "btn btn-primary" %>
            <% end %>
        <% elsif @vehicle.matching.present? %>
          <% if @vehicle.user_id == current_user.id %>
            
          <% end %>
        <% end %>
      </article>
      <% if @vehicle.matching.present? %>
        <% if @vehicle.user_id == current_user.id or @vehicle.matching.user.id == current_user.id %>
          <% if @vehicle.user_id == current_user.id %>
            <%= @vehicle.matching.user.name %>さんとのトーク
          <% else %>
            <%= @vehicle.user.name %>さんとのトーク
          <% end %>
          <%= render 'chats/chats', { chats: @chats } %>
          <%= render 'chats/form', { vehicle: @vehicle, chat: @chat } %>
        <% else %>
          <p>他の方が予約済みです</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $("#chats").scrollTop($("#chats")[0].scrollHeight);
</script>